// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://google.com/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://www.google.com/contact",
            "email": "support@google.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "do ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Login request OTP",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "MSISDN",
                        "name": "msisdn",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    }
                }
            }
        },
        "/auth/login-otp": {
            "post": {
                "description": "Login with OTP",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "Login With OTP",
                "parameters": [
                    {
                        "type": "string",
                        "description": "MSISDN",
                        "name": "msisdn",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OTP",
                        "name": "otp",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginWithOtpResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginWithOtpErrorResponse"
                        }
                    }
                }
            }
        },
        "/profile": {
            "post": {
                "description": "Profile API endpoint to retrieve user profile information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "Profile",
                "parameters": [
                    {
                        "description": "Profile Request",
                        "name": "profileRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved profile information.",
                        "schema": {
                            "$ref": "#/definitions/dto.ProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or authentication failure.",
                        "schema": {
                            "$ref": "#/definitions/dto.ProfileErrorResponse"
                        }
                    }
                }
            }
        },
        "/promo": {
            "post": {
                "description": "Promo API endpoint to retrieve promo information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "Promo",
                "parameters": [
                    {
                        "description": "Promo Request",
                        "name": "promoRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AllRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved promo information.",
                        "schema": {
                            "$ref": "#/definitions/dto.PromoResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or authentication failure.",
                        "schema": {
                            "$ref": "#/definitions/dto.PromoErrorResponse"
                        }
                    }
                }
            }
        },
        "/transaction": {
            "post": {
                "description": "Transaction API endpoint to retrieve transaction information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "Transaction",
                "parameters": [
                    {
                        "enum": [
                            "PULSA",
                            "PAKET",
                            "TRANSFER",
                            "HIBURAN",
                            "GAME"
                        ],
                        "type": "string",
                        "default": "PULSA",
                        "description": "Transaction Category",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ALL",
                            "SUCCESS",
                            "PENDING",
                            "FAILED"
                        ],
                        "type": "string",
                        "default": "ALL",
                        "description": "Transaction Status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "description": "Transaction Request",
                        "name": "transactionRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AllRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved transaction information.",
                        "schema": {
                            "$ref": "#/definitions/dto.TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or authentication failure.",
                        "schema": {
                            "$ref": "#/definitions/dto.TransactionErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AllRequest": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "callPlan": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "msisdn": {
                    "type": "string"
                },
                "secretKey": {
                    "type": "string"
                },
                "subscriberType": {
                    "type": "string"
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "dto.LoginWithOtpErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "dto.LoginWithOtpResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "appsflyerMsisdn": {
                    "type": "string"
                },
                "balance": {
                    "type": "string"
                },
                "callPlan": {
                    "type": "string"
                },
                "creditLimit": {
                    "type": "string"
                },
                "firstTime": {
                    "type": "boolean"
                },
                "language": {
                    "type": "string"
                },
                "msisdn": {
                    "type": "string"
                },
                "profileColor": {
                    "type": "string"
                },
                "profileTime": {
                    "type": "integer"
                },
                "secretKey": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "subscriberType": {
                    "type": "string"
                },
                "xlocation": {}
            }
        },
        "dto.ProfileErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "dto.ProfileRequest": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "callPlan": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "msisdn": {
                    "type": "string"
                },
                "secretKey": {
                    "type": "string"
                },
                "subscriberType": {
                    "type": "string"
                }
            }
        },
        "dto.ProfileResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "activePackages": {},
                        "balance": {
                            "type": "string"
                        },
                        "balanceDetails": {
                            "type": "object",
                            "properties": {
                                "balance": {
                                    "type": "object",
                                    "properties": {
                                        "title": {
                                            "type": "string"
                                        },
                                        "value": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "balanceOffnet": {},
                                "balanceOnAndOffNet": {
                                    "type": "object",
                                    "properties": {
                                        "detail": {
                                            "type": "object",
                                            "properties": {
                                                "Masa Berlaku": {
                                                    "type": "string"
                                                },
                                                "Sisa Pulsa": {
                                                    "type": "string"
                                                }
                                            }
                                        },
                                        "title": {
                                            "type": "string"
                                        },
                                        "value": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "balanceOnNet": {}
                            }
                        },
                        "balanceOffNet": {
                            "type": "string"
                        },
                        "balanceOnAndOffNet": {
                            "type": "string"
                        },
                        "balanceOnNet": {
                            "type": "string"
                        },
                        "balanceTotal": {
                            "type": "string"
                        },
                        "balanceTrims": {
                            "type": "string"
                        },
                        "birthDate": {},
                        "bonstriDetail": {
                            "type": "object",
                            "properties": {
                                "bonusPoint": {
                                    "type": "integer"
                                },
                                "loyaltyPoint": {
                                    "type": "integer"
                                },
                                "totalPoint": {
                                    "type": "integer"
                                },
                                "validityLoyaltyPoint": {
                                    "type": "integer"
                                }
                            }
                        },
                        "callPlan": {
                            "type": "string"
                        },
                        "cashback": {
                            "type": "string"
                        },
                        "creditLimit": {
                            "type": "string"
                        },
                        "creditLimitHybrid": {
                            "type": "string"
                        },
                        "customerSegmentation": {
                            "type": "object",
                            "properties": {
                                "deeplink": {},
                                "description": {
                                    "type": "string"
                                },
                                "segmentationName": {
                                    "type": "string"
                                },
                                "title": {
                                    "type": "string"
                                }
                            }
                        },
                        "dueDate": {
                            "type": "string"
                        },
                        "dueDateHybrid": {
                            "type": "string"
                        },
                        "dukcapilName": {
                            "type": "string"
                        },
                        "dukcapilUrl": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string"
                        },
                        "emailHybrid": {
                            "type": "string"
                        },
                        "firstLogin": {
                            "type": "string"
                        },
                        "lastLogin": {
                            "type": "string"
                        },
                        "maxPullNotification": {
                            "type": "integer"
                        },
                        "mgmReferralDetails": {
                            "type": "object",
                            "properties": {
                                "countOfReferrals": {
                                    "type": "integer"
                                },
                                "referralCode": {
                                    "type": "string"
                                },
                                "tncURL": {
                                    "type": "string"
                                },
                                "totalPoints": {
                                    "type": "integer"
                                }
                            }
                        },
                        "msisdn": {
                            "type": "string"
                        },
                        "packageList": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "detail": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "validity": {
                                                    "type": "string"
                                                },
                                                "value": {
                                                    "type": "string"
                                                },
                                                "valueOriginal": {}
                                            }
                                        }
                                    },
                                    "groupId": {
                                        "type": "string"
                                    },
                                    "isMore": {
                                        "type": "boolean"
                                    },
                                    "isProductBuy": {
                                        "type": "boolean"
                                    },
                                    "isRenewable": {
                                        "type": "boolean"
                                    },
                                    "isShareQuota": {
                                        "type": "boolean"
                                    },
                                    "linkProductBuyType": {
                                        "type": "string"
                                    },
                                    "linkProductBuyValue": {
                                        "type": "string"
                                    },
                                    "name": {
                                        "type": "string"
                                    },
                                    "productId": {}
                                }
                            }
                        },
                        "packageProductGroupList": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "content": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "allocated": {
                                                    "type": "string"
                                                },
                                                "allocatedRaw": {
                                                    "type": "string"
                                                },
                                                "bonusType": {
                                                    "type": "string"
                                                },
                                                "consumed": {
                                                    "type": "string"
                                                },
                                                "consumedRaw": {
                                                    "type": "string"
                                                },
                                                "isShareable": {
                                                    "type": "boolean"
                                                },
                                                "localQuota": {
                                                    "type": "boolean"
                                                },
                                                "productId": {},
                                                "remaining": {
                                                    "type": "string"
                                                },
                                                "remainingRaw": {
                                                    "type": "string"
                                                },
                                                "title": {
                                                    "type": "string"
                                                },
                                                "validity": {
                                                    "type": "string"
                                                },
                                                "validityRaw": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    },
                                    "currChildCount": {
                                        "type": "integer"
                                    },
                                    "isShareable": {
                                        "type": "boolean"
                                    },
                                    "isStoppable": {
                                        "type": "boolean"
                                    },
                                    "isTransferable": {
                                        "type": "boolean"
                                    },
                                    "listOfSharableQuota": {
                                        "type": "array",
                                        "items": {}
                                    },
                                    "maxChildCount": {
                                        "type": "integer"
                                    },
                                    "name": {
                                        "type": "string"
                                    },
                                    "productId": {},
                                    "shareQuota": {
                                        "type": "array",
                                        "items": {}
                                    }
                                }
                            }
                        },
                        "packageProductList": {
                            "type": "array",
                            "items": {}
                        },
                        "profileColor": {
                            "type": "string"
                        },
                        "profileHobby": {},
                        "profileName": {
                            "type": "string"
                        },
                        "profilePicture": {
                            "type": "string"
                        },
                        "profileTime": {
                            "type": "integer"
                        },
                        "status": {
                            "type": "boolean"
                        },
                        "statusSubscription": {
                            "type": "boolean"
                        },
                        "subscriberType": {
                            "type": "string"
                        },
                        "sumOfBonuses": {
                            "type": "object",
                            "properties": {
                                "Data": {
                                    "type": "string"
                                },
                                "SMS": {
                                    "type": "string"
                                },
                                "Voice": {
                                    "type": "string"
                                }
                            }
                        },
                        "validity": {
                            "type": "string"
                        }
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "title": {}
            }
        },
        "dto.PromoErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "dto.PromoResponse": {
            "type": "object",
            "properties": {
                "code": {},
                "data": {
                    "type": "object",
                    "properties": {
                        "child": {},
                        "color1": {
                            "type": "string"
                        },
                        "color2": {
                            "type": "string"
                        },
                        "color3": {
                            "type": "string"
                        },
                        "flagType": {},
                        "flagUrl": {},
                        "id": {
                            "type": "integer"
                        },
                        "id2": {
                            "type": "integer"
                        },
                        "image": {
                            "type": "string"
                        },
                        "isAutorotate": {},
                        "isCard": {},
                        "layoutId": {},
                        "mainCategoryId": {
                            "type": "integer"
                        },
                        "metadata": {},
                        "moreId": {},
                        "name": {
                            "type": "string"
                        },
                        "productList": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "active": {
                                        "type": "boolean"
                                    },
                                    "articleBody": {},
                                    "articleLayout": {},
                                    "articleTitle": {},
                                    "basePackage": {},
                                    "bonstriPoints": {},
                                    "buttonBuy": {
                                        "type": "string"
                                    },
                                    "campaign": {
                                        "type": "integer"
                                    },
                                    "categoryId": {},
                                    "customData": {},
                                    "customDataId": {},
                                    "customDataQuota": {},
                                    "deeplink": {},
                                    "downloadLink": {
                                        "type": "string"
                                    },
                                    "endDateTime": {
                                        "type": "string"
                                    },
                                    "flagType": {},
                                    "flagUrl": {},
                                    "gameProductCategory": {},
                                    "gamePurchaseType": {},
                                    "isActive": {
                                        "type": "boolean"
                                    },
                                    "isArticle": {
                                        "type": "boolean"
                                    },
                                    "isAutoRenewable": {
                                        "type": "integer"
                                    },
                                    "isBanner": {
                                        "type": "boolean"
                                    },
                                    "isDownloadLink": {
                                        "type": "boolean"
                                    },
                                    "isGamePartner": {
                                        "type": "boolean"
                                    },
                                    "isInappBrowser": {},
                                    "isInstallment": {},
                                    "isProductRedirection": {
                                        "type": "boolean"
                                    },
                                    "isRedemption": {
                                        "type": "boolean"
                                    },
                                    "isRedirectToLink": {
                                        "type": "boolean"
                                    },
                                    "isRequireGameIdVerification": {
                                        "type": "boolean"
                                    },
                                    "isRequireGameZoneIdVerification": {
                                        "type": "boolean"
                                    },
                                    "isShareable": {
                                        "type": "integer"
                                    },
                                    "isSquareBanner": {},
                                    "isTransferable": {
                                        "type": "integer"
                                    },
                                    "labelDescription": {
                                        "type": "string"
                                    },
                                    "labelDetails": {
                                        "type": "string"
                                    },
                                    "labelHowTo": {
                                        "type": "string"
                                    },
                                    "labelOtherInfo": {
                                        "type": "string"
                                    },
                                    "labelPricing": {
                                        "type": "string"
                                    },
                                    "metadata": {
                                        "type": "object",
                                        "properties": {
                                            "IMG_BANNER": {
                                                "type": "string"
                                            },
                                            "IMG_BANNER_BIG": {
                                                "type": "string"
                                            },
                                            "IMG_BREAKER": {
                                                "type": "string"
                                            },
                                            "IMG_BREAKER_BIG": {
                                                "type": "string"
                                            },
                                            "IMG_PRODUCT_PORTRAIT": {
                                                "type": "string"
                                            },
                                            "IMG_PRODUCT_PORTRAIT_BIG": {
                                                "type": "string"
                                            },
                                            "IMG_PRODUCT_SQUARE": {
                                                "type": "string"
                                            },
                                            "IMG_PRODUCT_SQUARE_BIG": {
                                                "type": "string"
                                            },
                                            "IMG_RFU": {
                                                "type": "string"
                                            },
                                            "IMG_RFU_BIG": {
                                                "type": "string"
                                            },
                                            "IMG_SMALL": {
                                                "type": "string"
                                            },
                                            "IMG_SMALL_BIG": {
                                                "type": "string"
                                            }
                                        }
                                    },
                                    "offerDetail": {},
                                    "parent": {
                                        "type": "boolean"
                                    },
                                    "parentLayoutId": {},
                                    "partnerId": {},
                                    "paymentList": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "methodCode": {
                                                    "type": "string"
                                                },
                                                "methodName": {
                                                    "type": "string"
                                                },
                                                "rest": {
                                                    "type": "boolean"
                                                }
                                            }
                                        }
                                    },
                                    "paymentMatrix": {
                                        "type": "array",
                                        "items": {
                                            "type": "integer"
                                        }
                                    },
                                    "productDescription": {
                                        "type": "string"
                                    },
                                    "productDetails": {
                                        "type": "object"
                                    },
                                    "productDetailsType": {
                                        "type": "string"
                                    },
                                    "productHowTo": {
                                        "type": "string"
                                    },
                                    "productId": {
                                        "type": "string"
                                    },
                                    "productLayout": {},
                                    "productName": {
                                        "type": "string"
                                    },
                                    "productOriginalPrice": {
                                        "type": "string"
                                    },
                                    "productOtherInfo": {},
                                    "productPrice": {
                                        "type": "string"
                                    },
                                    "productPricing": {
                                        "type": "string"
                                    },
                                    "productRating": {
                                        "type": "number"
                                    },
                                    "productRatingTotalUser": {
                                        "type": "integer"
                                    },
                                    "productValidity": {},
                                    "redirectLink": {
                                        "type": "string"
                                    },
                                    "startDateTime": {
                                        "type": "string"
                                    },
                                    "subMenuCategoryId": {},
                                    "tagDetail": {},
                                    "vendorList": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "priceList": {
                                                    "type": "array",
                                                    "items": {
                                                        "type": "object",
                                                        "properties": {
                                                            "planName": {
                                                                "type": "string"
                                                            },
                                                            "price": {
                                                                "type": "string"
                                                            }
                                                        }
                                                    }
                                                },
                                                "vendorId": {
                                                    "type": "integer"
                                                },
                                                "vendorName": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    },
                                    "zone": {}
                                }
                            }
                        },
                        "promoActiveFlag": {
                            "type": "boolean"
                        },
                        "promoEndDateTime": {
                            "type": "string"
                        },
                        "promoStartDateTime": {
                            "type": "string"
                        },
                        "promoType": {
                            "type": "string"
                        },
                        "survey": {},
                        "tagDetail": {},
                        "teaserEndDateTime": {},
                        "teaserImage": {},
                        "teaserStartDateTime": {},
                        "timePeriod": {}
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "title": {}
            }
        },
        "dto.TransactionErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "dto.TransactionResponse": {
            "type": "object",
            "properties": {
                "code": {},
                "data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "addon": {},
                            "category": {
                                "type": "string"
                            },
                            "dateReg": {
                                "type": "string"
                            },
                            "icon": {
                                "type": "string"
                            },
                            "isAddon": {
                                "type": "boolean"
                            },
                            "name": {
                                "type": "string"
                            },
                            "parentProductId": {
                                "type": "string"
                            },
                            "price": {
                                "type": "string"
                            },
                            "productId": {
                                "type": "string"
                            },
                            "status": {
                                "type": "string"
                            },
                            "target": {},
                            "transactionId": {
                                "type": "string"
                            }
                        }
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "title": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Bima TRI API",
	Description:      "This is bima tri api",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
